//
//  PublicSuffixRulesRegistry.swift
//  SwiftPublicSuffixList
//
//  Generated by Utilities/update-suffix.swift
//
//  Usage:
//  # cd $(SRCROOT)/Utilities
//  # swift update-suffix.swift

import Foundation

/// Provides access to the embedded Public Suffix List rules bundled with the package.
///
/// This class loads rules from the `registry.json` file included in the package bundle.
/// The embedded rules are useful for offline operation or as a fallback when online
/// fetching fails.
///
/// ## Overview
///
/// The rules are loaded lazily on first access to ``rules`` and cached for subsequent use.
/// The embedded list is updated periodically with the package releases, but may become
/// outdated between releases.
///
/// ## Updating the Embedded Rules
///
/// To update the embedded rules to the latest version, run the update script:
///
/// ```bash
/// cd Utilities
/// swift update-suffix.swift
/// ```
///
/// ## Usage
///
/// ```swift
/// // Access embedded rules directly
/// let rules = PublicSuffixRulesRegistry.rules
///
/// // Use with PublicSuffixList
/// let isValid = PublicSuffixList.isUnrestricted("example.com", rules: PublicSuffixRulesRegistry.rules)
/// ```
public final class PublicSuffixRulesRegistry {

    /// The embedded Public Suffix List rules.
    ///
    /// Rules are loaded from the bundled `registry.json` file on first access.
    /// Returns an empty array if the file cannot be found or decoded.
    ///
    /// Each rule is an array of domain labels in reverse order (TLD first).
    /// See ``PublicSuffixList/rules`` for details on the rule format.
    public static let rules: [[String]] = loadFromJson()
    
    private static func loadFromJson() -> [[String]] {
        guard let registryJsonUrl = Bundle.module.url(forResource: "registry", withExtension: "json") else {
            print("WARNING failed to read public suffix registry file: registry.json not found in bundle")
            return []
        }

        let registryRules: [[String]]
        do {
            let registryData = try Data(contentsOf: registryJsonUrl)
            registryRules = try JSONDecoder().decode([[String]].self, from: registryData)
        } catch {
            print("WARNING failed to read public suffix registry file:", error)
            registryRules = []
        }
        return registryRules
    }
}
